# -*- coding: utf-8 -*-
"""ai_business_insights.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v1FSdbHNegJKhkJXGS77CKvBpodsijtc
"""

import os
import pandas as pd
import google.generativeai as genai
from pathlib import Path

# -------------------------------
# Configure Gemini API
# -------------------------------
genai.configure(api_key="GEMINI_API_KEY")

model = genai.GenerativeModel("gemini-2.5-flash")

# -------------------------------
# Load datasets
# -------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "datasets"

customers = pd.read_csv(DATA_DIR / "olist_customers_dataset.csv")
orders = pd.read_csv(DATA_DIR / "olist_orders_dataset.csv")
payments = pd.read_csv(DATA_DIR / "olist_order_payments_dataset.csv")
products = pd.read_csv(DATA_DIR / "olist_products_dataset.csv")
# -------------------------------
# Calculate KPIs
# -------------------------------
total_revenue = payments["payment_value"].sum()
total_orders = len(orders)
total_customers = customers["customer_unique_id"].nunique()

top_state = customers["customer_state"].value_counts().idxmax()

top_category = (
    products["product_category_name"]
    .value_counts()
    .idxmax()
)

# -------------------------------
# Prompt
# -------------------------------
prompt = f"""
You are a Senior Business Analyst.

Analyze the following e-commerce KPIs.

Revenue: ₹{total_revenue:,.2f}
Orders: {total_orders}
Customers: {total_customers}
Top Customer State: {top_state}
Top Product Category: {top_category}

Generate:

1. Executive Summary
2. Three Key Business Insights
3. Three Actionable Recommendations

Keep the response professional and concise.
"""

# -------------------------------
# Generate AI Insights
# -------------------------------
response = model.generate_content(prompt)

print("\nAI BUSINESS INSIGHTS\n")
print(response.text)

